### ISSUE TITLE
[1차 세미나] 기본 과제 및 심화 과제

### ISSUE THREAD

**Issue by csb9427** [DO-SOPT-SERVER/csb9427#1]
## ✏️ TO-DO

- [x] 자바 기초 코드 작성
- [x] 스프링 기초 코드 작성
- [ ] 스프링 심화 코드 작성
